import type { NextPage } from 'next'
import Head from 'next/head'
import IconArrowRight from '~icons/dashicons/arrow-right.jsx'
import NextLogo from '~icons/logos/nextjs.jsx'
import VercelLogo from '~icons/logos/vercel.jsx'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to</h1>

        <a href="https://nextjs.org">
          <NextLogo width={307} height={185} />
        </a>

        <p className={styles.description}>
          Get started by editing
          {' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>
              Documentation
              {' '}
              <IconArrowRight />
            </h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>
              Learn
              {' '}
              <IconArrowRight />
            </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>
              Examples
              {' '}
              <IconArrowRight />
            </h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new" className={styles.card}>
            <h2>
              Deploy
              {' '}
              <IconArrowRight />
            </h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by&nbsp;
          <span className={styles.logo}>
            <VercelLogo width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
