ignoreWorkspaceRootCheck: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade

packages:
  - examples/*
  - '!examples/nuxt4'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - svelte-preprocess
