/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAppConnectivity: typeof import('~icons/carbon/app-connectivity')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IIcTwotone23mp: typeof import('~icons/ic/twotone23mp')['default']
    IIcTwotone24mp: typeof import('~icons/ic/twotone24mp')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    'IMdi:cactus': typeof import('~icons/mdi/cactus')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiDiceD12: typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    INotoV1FlagForFlagJapan: typeof import('~icons/noto-v1/flag-for-flag-japan')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
  }
}
