// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAppConnectivity: typeof import('~icons/carbon/app-connectivity')['default']
    ICustomCarA: typeof import('~icons/custom/car-a')['default']
    ICustomSteeringWheel: typeof import('~icons/custom/steering-wheel')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IIcTwotone23mp: typeof import('~icons/ic/twotone23mp')['default']
    IIcTwotone24mp: typeof import('~icons/ic/twotone24mp')['default']
    IInlineAsync: typeof import('~icons/inline/async')['default']
    IInlineFoo: typeof import('~icons/inline/foo')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    'IMdi:cactus': typeof import('~icons/mdi/cactus')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiDiceD12: typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    INotoV1FlagForFlagJapan: typeof import('~icons/noto-v1/flag-for-flag-japan')['default']
    IParkAbnormal: typeof import('~icons/icon-park/abnormal')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    ITwemoji1stPlaceMedal: typeof import('~icons/twemoji/1st-place-medal')['default']
  }
}

export { }
