// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAppConnectivity: typeof import('virtual:icons/carbon/app-connectivity')['default']
    IFaSolidDiceFive: typeof import('virtual:icons/fa-solid/dice-five')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('virtual:icons/heroicons-outline/menu-alt2')['default']
    IIcTwotone23mp: typeof import('virtual:icons/ic/twotone23mp')['default']
    IIcTwotone24mp: typeof import('virtual:icons/ic/twotone24mp')['default']
    ILogosVue: typeof import('virtual:icons/logos/vue')['default']
    'IMdi:cactus': typeof import('virtual:icons/mdi/cactus')['default']
    IMdiAccount: typeof import('virtual:icons/mdi/account')['default']
    IMdiDiceD12: typeof import('virtual:icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('virtual:icons/mdi-light/alarm')['default']
    INotoV1FlagForFlagJapan: typeof import('virtual:icons/noto-v1/flag-for-flag-japan')['default']
    IRiApps2Line: typeof import('virtual:icons/ri/apps2-line')['default']
    ITwemoji1stPlaceMedal: typeof import('virtual:icons/twemoji/1st-place-medal')['default']
  }
}

export { }
