name: Publish Any Commit
on: [push, pull_request]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release-commit.yml@v1
    with:
      compact: true
